---
ID: "ae2dea49-8158-52a1-b446-a82b5a958b90"
Parent: "cc1e51ba-dc8e-5250-9e04-22caecdf9663"
Template: "cc1e51ba-dc8e-5250-9e04-22caecdf9663"
Path: "/sitecore/templates/Project/altudohackathon/GraphQL-ConnectedDemo/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220107T181622Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e3a2ae8c-73df-42ce-9478-2e49e20fdfa5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220107T181622Z
