---
ID: "7eaf8b36-7466-5c23-ac3b-c70facadfe33"
Parent: "4d5d9e1c-b51e-51c2-88e5-b5627173bf01"
Template: "4d5d9e1c-b51e-51c2-88e5-b5627173bf01"
Path: /sitecore/templates/Project/altudohackathon/TitleTextImage/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220108T202525Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cfab9ffe-0295-4b92-a5d4-12127acbcbdf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220108T202525Z
