---
ID: "5a3b22eb-f8eb-560d-850a-275b8a4017d9"
Parent: "d38b7b47-7633-5e70-8672-4d589eefc0b5"
Template: "d38b7b47-7633-5e70-8672-4d589eefc0b5"
Path: /sitecore/templates/Project/altudohackathon/ContentBlock/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220107T181616Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7d19408d-7048-4ae9-9833-fc1c4cf3d06f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220107T181616Z
