---
ID: "3d052334-d8a3-58a0-96f4-89010d63fa75"
Parent: "013bd5e2-fb31-5978-b823-cd2da508dde8"
Template: "013bd5e2-fb31-5978-b823-cd2da508dde8"
Path: "/sitecore/templates/Project/altudohackathon/Styleguide-ContentList-Item-Template/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220107T181613Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e7f37995-ce6a-4a80-85a6-9c44db93ebe1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220107T181613Z
